### ISSUE TITLE
TensorRT support?

### ISSUE THREAD

**Issue by czzs** [ai-dock/stable-diffusion-webui#16]
Tried to add the [TensorRT github repo](https://github.com/AUTOMATIC1111/stable-diffusion-webui-tensorrt) to the provisioning script on vast.ai, but the install was not successful. I also tried to install it from the Extensions tab, but this broke the whole WebUI.

Has anyone figured out how to install TensorRT? Or is there any know issue why this does not work with this docker image?

Thanks in advance!

Update: after installing everything, this is the error message I always get:
`{"level":"error","ts":1712759896.8992972,"logger":"http.log.error","msg":"dial tcp 127.0.0.1:17860: connect: connection refused","request":{"remote_ip":"127.0.0.1","remote_port":"57394","client_ip":"127.0.0.1","proto":"HTTP/1.1","method":"GET","host":"confident-backup-parameters-software.trycloudflare.com","uri":"/","headers":{"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"],"Accept-Encoding":["gzip"],"Cf-Ray":["87237acb601e5bb9-VIE"],"Cf-Warp-Tag-Id":["9f39b7a1-932f-4a6b-bd34-b6d7aa242faf"],"Connection":["keep-alive"],"Cdn-Loop":["cloudflare; subreqs=1"],"Cf-Ew-Via":["15"],"Cf-Worker":["trycloudflare.com"],"Sec-Ch-Ua-Mobile":["?0"],"X-Forwarded-For":["176.63.202.78"],"Upgrade-Insecure-Requests":["1"],"Accept-Language":["en-GB,en-US;q=0.9,en;q=0.8"],"Cookie":[],"Referer":["http://213.181.123.100:28045/"],"Sec-Ch-Ua":["\"Google Chrome\";v=\"123\", \"Not:A-Brand\";v=\"8\", \"Chromium\";v=\"123\""],"Sec-Fetch-Mode":["navigate"],"Sec-Fetch-Site":["cross-site"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"],"Sec-Fetch-Dest":["document"],"X-Forwarded-Proto":["https"],"Cache-Control":["max-age=0"],"Cf-Connecting-Ip":["176.63.202.78"],"Cf-Ipcountry":["HU"],"Cf-Visitor":["{\"scheme\":\"https\"}"],"Sec-Ch-Ua-Platform":["\"macOS\""],"Sec-Fetch-User":["?1"]}},"duration":0.000448417,"status":502,"err_id":"b6mptumeq","err_trace":"reverseproxy.statusError (reverseproxy.go:1267)"}`

**Comment by phiberoptick** [comment]
I suspect it's because it's getting stuck trying to uninstall nvidia-cudnn-11 and waiting for user input.  Which means that the webui never actually starts in the container.  Can verify by checking with ss or netstat if the port specified in WEBUI_LOCAL env variable is actually listening. 

I was able to exec into the container and manually run `python -m pip uninstall nvidia-cudnn-11` to uninstall it.  I then restarted the webui (either the service via the service manager or the entire container).

After, it continued to install the rest of the requirements and started the webui properly.
